import { Component, h, Host } from '@stencil/core';
import { CupRounds, GameState, Stage, StageFormat, stageMocks, Team, teamMocks } from 'ftb-models';

@Component({
  tag: 'ftb-stage-cup-net-stories',
  styleUrl: 'ftb-stage-cup-net.stories.scss',
  shadow: false,
})
export class FtbStageCupNetStories {
  render() {
    return (
      <Host>
        <h1>New cup net</h1>
        <ftb-cup-net-quadratic stage={stageN} />

        <h1>Cup Net</h1>
        <ftb-code-snippet code="<ftb-stage-cup-net stage={stage} />" />
        <ftb-stage-cup-net stage={stage} />

        <h2>Highlighting</h2>
        <p>You can select team to highlight on the net</p>
        <ftb-code-snippet code="<ftb-stage-cup-net stage={stage} highlightTeam={new Team({ _id: 19417, name: 'Egrisi' })} />" />
        <ftb-stage-cup-net stage={stage} highlightTeam={new Team({ _id: 19417, name: 'Egrisi' })} />

        <h2>Autofill</h2>
        <p>If not all rounds exists, net will be filled with empty slots</p>
        <ftb-stage-cup-net stage={stageEmpty} />

        <h2>Ternary structure</h2>
        <p>If cup structure has ternary format, net will have different look</p>
        {/*<ftb-stage-cup-net stage={StageTernary} />*/}
      </Host>
    );
  }
}
const stageN = new Stage({
  ...stageMocks,
  ...{
    cupNet: [
      {
        _id: 1,
        netPosition: 0,
        tourNumber: CupRounds.final,
        stateCode: GameState.NOT_STARTED,
        teamHome: teamMocks.Chelsea,
        teamAway: teamMocks.Arsenal,
      },
      // {
      //   _id: 2,
      //   netPosition: 1,
      //   tourNumber: CupRounds['3rd_place'],
      //   stateCode: GameState.NOT_STARTED,
      //   teamHome: teamMocks.Barcelona,
      //   teamAway: teamMocks.Borussia,
      // },
      {
        _id: 3,
        netPosition: 0,
        tourNumber: CupRounds['1/2'],
        stateCode: GameState.CLOSED,
        teamHome: teamMocks.Barcelona,
        teamAway: teamMocks.Arsenal,
        scoreFtHome: 3,
        scoreFtAway: 5,
      },
      {
        _id: 4,
        netPosition: 0,
        tourNumber: CupRounds['1/2'],
        stateCode: GameState.CLOSED,
        teamHome: teamMocks.Barcelona,
        teamAway: teamMocks.Arsenal,
        scoreFtHome: 1,
        scoreFtAway: 2,
      },
      {
        _id: 5,
        netPosition: 1,
        tourNumber: CupRounds['1/2'],
        stateCode: GameState.CLOSED,
        teamHome: teamMocks.Chelsea,
        teamAway: teamMocks.Borussia,
        scoreFtHome: 2,
        scoreFtAway: 2,
      },
      {
        _id: 6,
        netPosition: 1,
        tourNumber: CupRounds['1/2'],
        stateCode: GameState.CLOSED,
        teamHome: teamMocks.Borussia,
        teamAway: teamMocks.Chelsea,
        scoreFtHome: 0,
        scoreFtAway: 0,
        scorePenHome: 5,
        scorePenAway: 3,
      },
    ],
  },
});

const stage = new Stage({
  _id: 10261,
  name: 'Play-Off',
  format: StageFormat.cup,
  sortIdx: 3,
  cupNet: [
    {
      _id: 406684,
      netPosition: 0,
      stateCode: 2,
      date: '2021-11-12T16:00:19.000Z',
      tourNumber: 0,
      scoreFtHome: 0,
      scoreFtAway: 0,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19417,
        name: 'Egrisi',
        shortName: 'EGR',
        logo: 'Egrisi',
        logoId: 1,
      },
      teamAway: {
        _id: 19056,
        name: 'Chievo',
        shortName: 'CHI',
        logo: 'Chievo',
        logoId: 1,
      },
    },
    {
      _id: 405311,
      netPosition: 0,
      stateCode: 4,
      date: '2021-10-10T13:20:00.000Z',
      tourNumber: 2,
      scoreFtHome: 3,
      scoreFtAway: 3,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 18537,
        name: 'Benfica',
        shortName: 'BEN',
        logo: 'Benfica',
        logoId: 2,
      },
      teamAway: {
        _id: 19417,
        name: 'Egrisi',
        shortName: 'EGR',
        logo: 'Egrisi',
        logoId: 1,
      },
    },
    {
      _id: 404987,
      netPosition: 0,
      stateCode: 4,
      date: '2021-10-15T15:40:00.000Z',
      tourNumber: 1,
      scoreFtHome: 2,
      scoreFtAway: 3,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 18736,
        name: 'Fiorentina',
        shortName: 'FIO',
        logo: 'Fiorentina',
        logoId: 1,
      },
      teamAway: {
        _id: 19417,
        name: 'Egrisi',
        shortName: 'EGR',
        logo: 'Egrisi',
        logoId: 1,
      },
    },
    {
      _id: 404943,
      netPosition: 0,
      stateCode: 4,
      date: '2021-10-02T12:40:00.000Z',
      tourNumber: 2,
      scoreFtHome: 5,
      scoreFtAway: 3,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19417,
        name: 'Egrisi',
        shortName: 'EGR',
        logo: 'Egrisi',
        logoId: 1,
      },
      teamAway: {
        _id: 18537,
        name: 'Benfica',
        shortName: 'BEN',
        logo: 'Benfica',
        logoId: 2,
      },
    },
    {
      _id: 405956,
      netPosition: 0,
      stateCode: 4,
      date: '2021-10-22T15:40:00.000Z',
      tourNumber: 1,
      scoreFtHome: 8,
      scoreFtAway: 4,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19417,
        name: 'Egrisi',
        shortName: 'EGR',
        logo: 'Egrisi',
        logoId: 1,
      },
      teamAway: {
        _id: 18736,
        name: 'Fiorentina',
        shortName: 'FIO',
        logo: 'Fiorentina',
        logoId: 1,
      },
    },
    {
      _id: 404988,
      netPosition: 1,
      stateCode: 4,
      date: '2021-10-17T14:30:00.000Z',
      tourNumber: 1,
      scoreFtHome: 2,
      scoreFtAway: 2,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19056,
        name: 'Chievo',
        shortName: 'CHI',
        logo: 'Chievo',
        logoId: 1,
      },
      teamAway: {
        _id: 25373,
        name: 'Lokomotiv',
        shortName: 'LOK',
        logo: 'Lokomotiv Moscow',
        logoId: 0,
      },
    },
    {
      _id: 405957,
      netPosition: 1,
      stateCode: 4,
      date: '2021-10-24T15:40:00.000Z',
      tourNumber: 1,
      scoreFtHome: 0,
      scoreFtAway: 5,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 25373,
        name: 'Lokomotiv',
        shortName: 'LOK',
        logo: 'Lokomotiv Moscow',
        logoId: 0,
      },
      teamAway: {
        _id: 19056,
        name: 'Chievo',
        shortName: 'CHI',
        logo: 'Chievo',
        logoId: 1,
      },
    },
    {
      _id: 405312,
      netPosition: 2,
      stateCode: 4,
      date: '2021-10-10T15:20:00.000Z',
      tourNumber: 2,
      scoreFtHome: 1,
      scoreFtAway: 6,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19032,
        name: 'LA Galaxy',
        shortName: 'LAG',
        logo: 'LA Galaxy',
        logoId: 1,
      },
      teamAway: {
        _id: 19056,
        name: 'Chievo',
        shortName: 'CHI',
        logo: 'Chievo',
        logoId: 1,
      },
    },
    {
      _id: 404944,
      netPosition: 2,
      stateCode: 4,
      date: '2021-10-01T14:50:00.000Z',
      tourNumber: 2,
      scoreFtHome: 8,
      scoreFtAway: 2,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19056,
        name: 'Chievo',
        shortName: 'CHI',
        logo: 'Chievo',
        logoId: 1,
      },
      teamAway: {
        _id: 19032,
        name: 'LA Galaxy',
        shortName: 'LAG',
        logo: 'LA Galaxy',
        logoId: 1,
      },
    },
    {
      _id: 404944,
      netPosition: 3,
      stateCode: 4,
      date: '2021-10-01T14:50:00.000Z',
      tourNumber: 2,
      scoreFtHome: 3,
      scoreFtAway: 1,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 25373,
        name: 'Lokomotiv',
        shortName: 'LOK',
        logo: 'Lokomotiv Moscow',
        logoId: 1,
      },
      teamAway: {
        _id: 123,
        name: 'Chelsea',
        shortName: 'CHE',
        logo: 'Chelsea',
        logoId: 1,
      },
    },
    {
      _id: 404944,
      netPosition: 3,
      stateCode: 4,
      date: '2021-10-01T14:50:00.000Z',
      tourNumber: 2,
      scoreFtHome: 1,
      scoreFtAway: 1,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 25373,
        name: 'Lokomotiv',
        shortName: 'LOK',
        logo: 'Lokomotiv Moscow',
        logoId: 1,
      },
      teamAway: {
        _id: 123,
        name: 'Chelsea',
        shortName: 'CHE',
        logo: 'Chelsea',
        logoId: 1,
      },
    },
    {
      _id: 405956,
      netPosition: 1,
      stateCode: 4,
      date: '2021-10-22T15:40:00.000Z',
      tourNumber: 2,
      scoreFtHome: 1,
      scoreFtAway: 2,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 321,
        name: 'Arsenal',
        shortName: 'Ars',
        logo: 'Arsenal',
        logoId: 1,
      },
      teamAway: {
        _id: 18736,
        name: 'Fiorentina',
        shortName: 'FIO',
        logo: 'Fiorentina',
        logoId: 1,
      },
    },
    {
      _id: 405956,
      netPosition: 1,
      stateCode: 4,
      date: '2021-10-22T15:40:00.000Z',
      tourNumber: 2,
      scoreFtHome: 2,
      scoreFtAway: 3,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 321,
        name: 'Arsenal',
        shortName: 'Ars',
        logo: 'Arsenal',
        logoId: 1,
      },
      teamAway: {
        _id: 18736,
        name: 'Fiorentina',
        shortName: 'FIO',
        logo: 'Fiorentina',
        logoId: 1,
      },
    },
  ],
});

const stageEmpty = new Stage({
  _id: 10261,
  name: 'Play-Off',
  format: StageFormat.cup,
  sortIdx: 3,
  cupNet: [
    {
      _id: 405312,
      netPosition: 2,
      stateCode: 4,
      date: '2021-10-10T15:20:00.000Z',
      tourNumber: 2,
      scoreFtHome: 1,
      scoreFtAway: 6,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19032,
        name: 'LA Galaxy',
        shortName: 'LAG',
        logo: 'LA Galaxy',
        logoId: 1,
      },
      teamAway: {
        _id: 19056,
        name: 'Chievo',
        shortName: 'CHI',
        logo: 'Chievo',
        logoId: 1,
      },
    },
    {
      _id: 404944,
      netPosition: 2,
      stateCode: 4,
      date: '2021-10-01T14:50:00.000Z',
      tourNumber: 2,
      scoreFtHome: 8,
      scoreFtAway: 2,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19056,
        name: 'Chievo',
        shortName: 'CHI',
        logo: 'Chievo',
        logoId: 1,
      },
      teamAway: {
        _id: 19032,
        name: 'LA Galaxy',
        shortName: 'LAG',
        logo: 'LA Galaxy',
        logoId: 1,
      },
    },
    {
      _id: 404944,
      netPosition: 3,
      stateCode: 4,
      date: '2021-10-01T14:50:00.000Z',
      tourNumber: 2,
      scoreFtHome: 3,
      scoreFtAway: 1,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 25373,
        name: 'Lokomotiv',
        shortName: 'LOK',
        logo: 'Lokomotiv Moscow',
        logoId: 1,
      },
      teamAway: {
        _id: 123,
        name: 'Chelsea',
        shortName: 'CHE',
        logo: 'Chelsea',
        logoId: 1,
      },
    },
    {
      _id: 404944,
      netPosition: 3,
      stateCode: 4,
      date: '2021-10-01T14:50:00.000Z',
      tourNumber: 2,
      scoreFtHome: 1,
      scoreFtAway: 1,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 25373,
        name: 'Lokomotiv',
        shortName: 'LOK',
        logo: 'Lokomotiv Moscow',
        logoId: 1,
      },
      teamAway: {
        _id: 123,
        name: 'Chelsea',
        shortName: 'CHE',
        logo: 'Chelsea',
        logoId: 1,
      },
    },
    {
      _id: 405956,
      netPosition: 1,
      stateCode: 4,
      date: '2021-10-22T15:40:00.000Z',
      tourNumber: 2,
      scoreFtHome: 1,
      scoreFtAway: 2,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 321,
        name: 'Arsenal',
        shortName: 'Ars',
        logo: 'Arsenal',
        logoId: 1,
      },
      teamAway: {
        _id: 18736,
        name: 'Fiorentina',
        shortName: 'FIO',
        logo: 'Fiorentina',
        logoId: 1,
      },
    },
    {
      _id: 405956,
      netPosition: 1,
      stateCode: 4,
      date: '2021-10-22T15:40:00.000Z',
      tourNumber: 2,
      scoreFtHome: 2,
      scoreFtAway: 3,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 321,
        name: 'Arsenal',
        shortName: 'Ars',
        logo: 'Arsenal',
        logoId: 1,
      },
      teamAway: {
        _id: 18736,
        name: 'Fiorentina',
        shortName: 'FIO',
        logo: 'Fiorentina',
        logoId: 1,
      },
    },
  ],
});

// const StageTernary = new Stage({
//   _id: 10262,
//   name: 'Play-Off',
//   format: StageFormat.cup,
//   sortIdx: 3,
//   cupNet: [
//     {
//       teamHome: {
//         _id: 123,
//         name: 'Chelsea',
//         shortName: 'CHE',
//         logo: 'Chelsea',
//         logoId: 1,
//       },
//       teamAway: {
//         _id: 25373,
//         name: 'Lokomotiv',
//         shortName: 'LOK',
//         logo: 'Lokomotiv Moscow',
//         logoId: 1,
//       },
//       scoreFtHome: 3,
//       scoreFtAway: 2,
//       techDefeat: false,
//       stateCode: GameState.CLOSED,
//       tourNumber: 9,
//       netPosition: 0,
//     },
//     {
//       teamHome: {
//         _id: 123,
//         name: 'Chelsea',
//         shortName: 'CHE',
//         logo: 'Chelsea',
//         logoId: 1,
//       },
//       teamAway: {
//         _id: 25373,
//         name: 'Lokomotiv',
//         shortName: 'LOK',
//         logo: 'Lokomotiv Moscow',
//         logoId: 1,
//       },
//       scoreFtHome: 5,
//       scoreFtAway: 4,
//       techDefeat: false,
//       stateCode: GameState.CLOSED,
//       tourNumber: 9,
//       netPosition: 1,
//     },
//     {
//       teamHome: {
//         _id: 123,
//         name: 'Chelsea',
//         shortName: 'CHE',
//         logo: 'Chelsea',
//         logoId: 1,
//       },
//       teamAway: {
//         _id: 25373,
//         name: 'Lokomotiv',
//         shortName: 'LOK',
//         logo: 'Lokomotiv Moscow',
//         logoId: 1,
//       },
//       scoreFtHome: 5,
//       scoreFtAway: 4,
//       techDefeat: false,
//       stateCode: GameState.CLOSED,
//       tourNumber: 9,
//       netPosition: 2,
//     },
//     {
//       teamHome: {
//         _id: 123,
//         name: 'Chelsea',
//         shortName: 'CHE',
//         logo: 'Chelsea',
//         logoId: 1,
//       },
//       teamAway: {
//         _id: 25373,
//         name: 'Lokomotiv',
//         shortName: 'LOK',
//         logo: 'Lokomotiv Moscow',
//         logoId: 1,
//       },
//       scoreFtHome: 2,
//       scoreFtAway: 2,
//       scorePenHome: 5,
//       scorePenAway: 3,
//       techDefeat: false,
//       stateCode: GameState.CLOSED,
//       tourNumber: 9,
//       netPosition: 3,
//     },
//
//     {
//       teamHome: {
//         _id: 123,
//         name: 'Chelsea',
//         shortName: 'CHE',
//         logo: 'Chelsea',
//         logoId: 1,
//       },
//       teamAway: {
//         _id: 25373,
//         name: 'Lokomotiv',
//         shortName: 'LOK',
//         logo: 'Lokomotiv Moscow',
//         logoId: 1,
//       },
//       scoreFtHome: 2,
//       scoreFtAway: 2,
//       scorePenHome: 3,
//       scorePenAway: 1,
//       techDefeat: false,
//       stateCode: GameState.CLOSED,
//       tourNumber: 9,
//       netPosition: 4,
//     },
//     {
//       teamHome: {
//         _id: 123,
//         name: 'Chelsea',
//         shortName: 'CHE',
//         logo: 'Chelsea',
//         logoId: 1,
//       },
//       teamAway: {
//         _id: 25373,
//         name: 'Lokomotiv',
//         shortName: 'LOK',
//         logo: 'Lokomotiv Moscow',
//         logoId: 1,
//       },
//       scoreFtHome: 2,
//       scoreFtAway: 0,
//       techDefeat: false,
//       stateCode: GameState.CLOSED,
//       tourNumber: 9,
//       netPosition: 5,
//     },
//
//     {
//       teamHome: {
//         _id: 123,
//         name: 'Chelsea',
//         shortName: 'CHE',
//         logo: 'Chelsea',
//         logoId: 1,
//       },
//       teamAway: {
//         _id: 25373,
//         name: 'Lokomotiv',
//         shortName: 'LOK',
//         logo: 'Lokomotiv Moscow',
//         logoId: 1,
//       },
//       scoreFtHome: 1,
//       scoreFtAway: 2,
//       techDefeat: false,
//       stateCode: GameState.CLOSED,
//       tourNumber: 8,
//       netPosition: 0,
//     },
//     {
//       teamHome: {
//         _id: 123,
//         name: 'Chelsea',
//         shortName: 'CHE',
//         logo: 'Chelsea',
//         logoId: 1,
//       },
//       teamAway: {
//         _id: 25373,
//         name: 'Lokomotiv',
//         shortName: 'LOK',
//         logo: 'Lokomotiv Moscow',
//         logoId: 1,
//       },
//       scoreFtHome: 6,
//       scoreFtAway: 2,
//       techDefeat: false,
//       stateCode: GameState.CLOSED,
//       tourNumber: 8,
//       netPosition: 1,
//     },
//     {
//       teamHome: {
//         _id: 123,
//         name: 'Chelsea',
//         shortName: 'CHE',
//         logo: 'Chelsea',
//         logoId: 1,
//       },
//       teamAway: {
//         _id: 25373,
//         name: 'Lokomotiv',
//         shortName: 'LOK',
//         logo: 'Lokomotiv Moscow',
//         logoId: 1,
//       },
//       scoreFtHome: 4,
//       scoreFtAway: 0,
//       techDefeat: false,
//       stateCode: GameState.CLOSED,
//       tourNumber: 8,
//       netPosition: 2,
//     },
//
//     {
//       teamHome: {
//         _id: 123,
//         name: 'Chelsea',
//         shortName: 'CHE',
//         logo: 'Chelsea',
//         logoId: 1,
//       },
//       teamAway: {
//         _id: 25373,
//         name: 'Lokomotiv',
//         shortName: 'LOK',
//         logo: 'Lokomotiv Moscow',
//         logoId: 1,
//       },
//       techDefeat: false,
//       stateCode: GameState.CLOSED,
//       tourNumber: 0,
//       netPosition: 0,
//     },
//     {
//       teamHome: {
//         _id: 123,
//         name: 'Chelsea',
//         shortName: 'CHE',
//         logo: 'Chelsea',
//         logoId: 1,
//       },
//       teamAway: {
//         _id: 25373,
//         name: 'Lokomotiv',
//         shortName: 'LOK',
//         logo: 'Lokomotiv Moscow',
//         logoId: 1,
//       },
//       techDefeat: false,
//       stateCode: GameState.CLOSED,
//       tourNumber: 0,
//       netPosition: 0,
//     },
//     {
//       teamHome: {
//         _id: 123,
//         name: 'Chelsea',
//         shortName: 'CHE',
//         logo: 'Chelsea',
//         logoId: 1,
//       },
//       teamAway: {
//         _id: 25373,
//         name: 'Lokomotiv',
//         shortName: 'LOK',
//         logo: 'Lokomotiv Moscow',
//         logoId: 1,
//       },
//       techDefeat: false,
//       stateCode: GameState.CLOSED,
//       tourNumber: 0,
//       netPosition: 0,
//     },
//   ],
// });
