import { Component, h, Host } from '@stencil/core';
import { Stage, StageFormat, Team } from 'ftb-models';

@Component({
  tag: 'ftb-stage-cup-net-stories',
  styleUrl: 'ftb-stage-cup-net.stories.scss',
  shadow: false,
})
export class FtbStageCupNetStories {
  render() {
    return (
      <Host>
        <h1>Cup Net</h1>
        <ftb-code-snippet code="<ftb-stage-cup-net stage={stage} />" />
        <ftb-stage-cup-net stage={stage} />

        <h2>Highlighting</h2>
        <p>You can select team to highlight on the net</p>
        <ftb-code-snippet code="<ftb-stage-cup-net stage={stage} highlightTeam={new Team({ _id: 19417, name: 'Egrisi' })} />" />
        <ftb-stage-cup-net stage={stage} highlightTeam={new Team({ _id: 19417, name: 'Egrisi' })} />

        <h2>Autofill</h2>
        <p>If not all rounds exists, net will be filled with empty slots</p>
        <ftb-stage-cup-net stage={stageEmpty} />

        <h2>Short/Compact mode</h2>
        <p>
          Yon can pass <code>short</code> or <code>compact</code> mode parameter to make cup net look better in narrow
          containers
        </p>
        <ftb-stage-cup-net stage={stage} mode="compact" />

        <h2>Ternary structure</h2>
        <p>If cup structure has ternary format, net will have different look</p>
      </Host>
    );
  }
}

const stage = new Stage({
  _id: 10261,
  name: 'Play-Off',
  format: StageFormat.cup,
  sortIdx: 3,
  cupNet: [
    {
      _id: 406684,
      netPosition: 0,
      stateCode: 2,
      date: '2021-11-12T16:00:19.000Z',
      tourNumber: 0,
      scoreFtHome: 0,
      scoreFtAway: 0,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19417,
        name: 'Egrisi',
        shortName: 'EGR',
        logo: 'Egrisi',
        logoId: 1,
      },
      teamAway: {
        _id: 19056,
        name: 'Chievo',
        shortName: 'CHI',
        logo: 'Chievo',
        logoId: 1,
      },
    },
    {
      _id: 405311,
      netPosition: 0,
      stateCode: 4,
      date: '2021-10-10T13:20:00.000Z',
      tourNumber: 2,
      scoreFtHome: 3,
      scoreFtAway: 3,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 18537,
        name: 'Benfica',
        shortName: 'BEN',
        logo: 'Benfica',
        logoId: 2,
      },
      teamAway: {
        _id: 19417,
        name: 'Egrisi',
        shortName: 'EGR',
        logo: 'Egrisi',
        logoId: 1,
      },
    },
    {
      _id: 404987,
      netPosition: 0,
      stateCode: 4,
      date: '2021-10-15T15:40:00.000Z',
      tourNumber: 1,
      scoreFtHome: 2,
      scoreFtAway: 3,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 18736,
        name: 'Fiorentina',
        shortName: 'FIO',
        logo: 'Fiorentina',
        logoId: 1,
      },
      teamAway: {
        _id: 19417,
        name: 'Egrisi',
        shortName: 'EGR',
        logo: 'Egrisi',
        logoId: 1,
      },
    },
    {
      _id: 404943,
      netPosition: 0,
      stateCode: 4,
      date: '2021-10-02T12:40:00.000Z',
      tourNumber: 2,
      scoreFtHome: 5,
      scoreFtAway: 3,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19417,
        name: 'Egrisi',
        shortName: 'EGR',
        logo: 'Egrisi',
        logoId: 1,
      },
      teamAway: {
        _id: 18537,
        name: 'Benfica',
        shortName: 'BEN',
        logo: 'Benfica',
        logoId: 2,
      },
    },
    {
      _id: 405956,
      netPosition: 0,
      stateCode: 4,
      date: '2021-10-22T15:40:00.000Z',
      tourNumber: 1,
      scoreFtHome: 8,
      scoreFtAway: 4,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19417,
        name: 'Egrisi',
        shortName: 'EGR',
        logo: 'Egrisi',
        logoId: 1,
      },
      teamAway: {
        _id: 18736,
        name: 'Fiorentina',
        shortName: 'FIO',
        logo: 'Fiorentina',
        logoId: 1,
      },
    },
    {
      _id: 404988,
      netPosition: 1,
      stateCode: 4,
      date: '2021-10-17T14:30:00.000Z',
      tourNumber: 1,
      scoreFtHome: 2,
      scoreFtAway: 2,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19056,
        name: 'Chievo',
        shortName: 'CHI',
        logo: 'Chievo',
        logoId: 1,
      },
      teamAway: {
        _id: 25373,
        name: 'Lokomotiv',
        shortName: 'LOK',
        logo: 'Lokomotiv Moscow',
        logoId: 0,
      },
    },
    {
      _id: 405957,
      netPosition: 1,
      stateCode: 4,
      date: '2021-10-24T15:40:00.000Z',
      tourNumber: 1,
      scoreFtHome: 0,
      scoreFtAway: 5,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 25373,
        name: 'Lokomotiv',
        shortName: 'LOK',
        logo: 'Lokomotiv Moscow',
        logoId: 0,
      },
      teamAway: {
        _id: 19056,
        name: 'Chievo',
        shortName: 'CHI',
        logo: 'Chievo',
        logoId: 1,
      },
    },
    {
      _id: 405312,
      netPosition: 2,
      stateCode: 4,
      date: '2021-10-10T15:20:00.000Z',
      tourNumber: 2,
      scoreFtHome: 1,
      scoreFtAway: 6,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19032,
        name: 'LA Galaxy',
        shortName: 'LAG',
        logo: 'LA Galaxy',
        logoId: 1,
      },
      teamAway: {
        _id: 19056,
        name: 'Chievo',
        shortName: 'CHI',
        logo: 'Chievo',
        logoId: 1,
      },
    },
    {
      _id: 404944,
      netPosition: 2,
      stateCode: 4,
      date: '2021-10-01T14:50:00.000Z',
      tourNumber: 2,
      scoreFtHome: 8,
      scoreFtAway: 2,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19056,
        name: 'Chievo',
        shortName: 'CHI',
        logo: 'Chievo',
        logoId: 1,
      },
      teamAway: {
        _id: 19032,
        name: 'LA Galaxy',
        shortName: 'LAG',
        logo: 'LA Galaxy',
        logoId: 1,
      },
    },
    {
      _id: 404944,
      netPosition: 3,
      stateCode: 4,
      date: '2021-10-01T14:50:00.000Z',
      tourNumber: 2,
      scoreFtHome: 3,
      scoreFtAway: 1,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 25373,
        name: 'Lokomotiv',
        shortName: 'LOK',
        logo: 'Lokomotiv Moscow',
        logoId: 1,
      },
      teamAway: {
        _id: 123,
        name: 'Chelsea',
        shortName: 'CHE',
        logo: 'Chelsea',
        logoId: 1,
      },
    },
    {
      _id: 404944,
      netPosition: 3,
      stateCode: 4,
      date: '2021-10-01T14:50:00.000Z',
      tourNumber: 2,
      scoreFtHome: 1,
      scoreFtAway: 1,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 25373,
        name: 'Lokomotiv',
        shortName: 'LOK',
        logo: 'Lokomotiv Moscow',
        logoId: 1,
      },
      teamAway: {
        _id: 123,
        name: 'Chelsea',
        shortName: 'CHE',
        logo: 'Chelsea',
        logoId: 1,
      },
    },
    {
      _id: 405956,
      netPosition: 1,
      stateCode: 4,
      date: '2021-10-22T15:40:00.000Z',
      tourNumber: 2,
      scoreFtHome: 1,
      scoreFtAway: 2,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 321,
        name: 'Arsenal',
        shortName: 'Ars',
        logo: 'Arsenal',
        logoId: 1,
      },
      teamAway: {
        _id: 18736,
        name: 'Fiorentina',
        shortName: 'FIO',
        logo: 'Fiorentina',
        logoId: 1,
      },
    },
    {
      _id: 405956,
      netPosition: 1,
      stateCode: 4,
      date: '2021-10-22T15:40:00.000Z',
      tourNumber: 2,
      scoreFtHome: 2,
      scoreFtAway: 3,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 321,
        name: 'Arsenal',
        shortName: 'Ars',
        logo: 'Arsenal',
        logoId: 1,
      },
      teamAway: {
        _id: 18736,
        name: 'Fiorentina',
        shortName: 'FIO',
        logo: 'Fiorentina',
        logoId: 1,
      },
    },
  ],
});

const stageEmpty = new Stage({
  _id: 10261,
  name: 'Play-Off',
  format: StageFormat.cup,
  sortIdx: 3,
  cupNet: [
    {
      _id: 405312,
      netPosition: 2,
      stateCode: 4,
      date: '2021-10-10T15:20:00.000Z',
      tourNumber: 2,
      scoreFtHome: 1,
      scoreFtAway: 6,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19032,
        name: 'LA Galaxy',
        shortName: 'LAG',
        logo: 'LA Galaxy',
        logoId: 1,
      },
      teamAway: {
        _id: 19056,
        name: 'Chievo',
        shortName: 'CHI',
        logo: 'Chievo',
        logoId: 1,
      },
    },
    {
      _id: 404944,
      netPosition: 2,
      stateCode: 4,
      date: '2021-10-01T14:50:00.000Z',
      tourNumber: 2,
      scoreFtHome: 8,
      scoreFtAway: 2,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 19056,
        name: 'Chievo',
        shortName: 'CHI',
        logo: 'Chievo',
        logoId: 1,
      },
      teamAway: {
        _id: 19032,
        name: 'LA Galaxy',
        shortName: 'LAG',
        logo: 'LA Galaxy',
        logoId: 1,
      },
    },
    {
      _id: 404944,
      netPosition: 3,
      stateCode: 4,
      date: '2021-10-01T14:50:00.000Z',
      tourNumber: 2,
      scoreFtHome: 3,
      scoreFtAway: 1,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 25373,
        name: 'Lokomotiv',
        shortName: 'LOK',
        logo: 'Lokomotiv Moscow',
        logoId: 1,
      },
      teamAway: {
        _id: 123,
        name: 'Chelsea',
        shortName: 'CHE',
        logo: 'Chelsea',
        logoId: 1,
      },
    },
    {
      _id: 404944,
      netPosition: 3,
      stateCode: 4,
      date: '2021-10-01T14:50:00.000Z',
      tourNumber: 2,
      scoreFtHome: 1,
      scoreFtAway: 1,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 25373,
        name: 'Lokomotiv',
        shortName: 'LOK',
        logo: 'Lokomotiv Moscow',
        logoId: 1,
      },
      teamAway: {
        _id: 123,
        name: 'Chelsea',
        shortName: 'CHE',
        logo: 'Chelsea',
        logoId: 1,
      },
    },
    {
      _id: 405956,
      netPosition: 1,
      stateCode: 4,
      date: '2021-10-22T15:40:00.000Z',
      tourNumber: 2,
      scoreFtHome: 1,
      scoreFtAway: 2,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 321,
        name: 'Arsenal',
        shortName: 'Ars',
        logo: 'Arsenal',
        logoId: 1,
      },
      teamAway: {
        _id: 18736,
        name: 'Fiorentina',
        shortName: 'FIO',
        logo: 'Fiorentina',
        logoId: 1,
      },
    },
    {
      _id: 405956,
      netPosition: 1,
      stateCode: 4,
      date: '2021-10-22T15:40:00.000Z',
      tourNumber: 2,
      scoreFtHome: 2,
      scoreFtAway: 3,
      scorePenHome: null,
      scorePenAway: null,
      teamHome: {
        _id: 321,
        name: 'Arsenal',
        shortName: 'Ars',
        logo: 'Arsenal',
        logoId: 1,
      },
      teamAway: {
        _id: 18736,
        name: 'Fiorentina',
        shortName: 'FIO',
        logo: 'Fiorentina',
        logoId: 1,
      },
    },
  ],
});
