/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Player } from "ftb-models/dist/models/player.model";
import { FtbTeamLogoMode } from "./components/ftb-team-logo/ftb-team-logo-mode";
import { Team } from "ftb-models/dist/models/team.model";
import { User } from "ftb-models/dist/models/user.model";
export namespace Components {
    interface CmpShowcase {
    }
    interface FtbIcon {
        "svg": string;
    }
    interface FtbImg {
        "name": string;
        "src": string;
    }
    interface FtbPlayerPhoto {
        "player": Player;
        "playerId": number;
        "version": number;
    }
    interface FtbTeamLogo {
        "logo": string;
        "mode": FtbTeamLogoMode;
        "name": string;
        "team": Team;
        "version": number;
    }
    interface FtbUserPhoto {
        "user": User;
        "userId": number;
        "version": number;
    }
}
declare global {
    interface HTMLCmpShowcaseElement extends Components.CmpShowcase, HTMLStencilElement {
    }
    var HTMLCmpShowcaseElement: {
        prototype: HTMLCmpShowcaseElement;
        new (): HTMLCmpShowcaseElement;
    };
    interface HTMLFtbIconElement extends Components.FtbIcon, HTMLStencilElement {
    }
    var HTMLFtbIconElement: {
        prototype: HTMLFtbIconElement;
        new (): HTMLFtbIconElement;
    };
    interface HTMLFtbImgElement extends Components.FtbImg, HTMLStencilElement {
    }
    var HTMLFtbImgElement: {
        prototype: HTMLFtbImgElement;
        new (): HTMLFtbImgElement;
    };
    interface HTMLFtbPlayerPhotoElement extends Components.FtbPlayerPhoto, HTMLStencilElement {
    }
    var HTMLFtbPlayerPhotoElement: {
        prototype: HTMLFtbPlayerPhotoElement;
        new (): HTMLFtbPlayerPhotoElement;
    };
    interface HTMLFtbTeamLogoElement extends Components.FtbTeamLogo, HTMLStencilElement {
    }
    var HTMLFtbTeamLogoElement: {
        prototype: HTMLFtbTeamLogoElement;
        new (): HTMLFtbTeamLogoElement;
    };
    interface HTMLFtbUserPhotoElement extends Components.FtbUserPhoto, HTMLStencilElement {
    }
    var HTMLFtbUserPhotoElement: {
        prototype: HTMLFtbUserPhotoElement;
        new (): HTMLFtbUserPhotoElement;
    };
    interface HTMLElementTagNameMap {
        "cmp-showcase": HTMLCmpShowcaseElement;
        "ftb-icon": HTMLFtbIconElement;
        "ftb-img": HTMLFtbImgElement;
        "ftb-player-photo": HTMLFtbPlayerPhotoElement;
        "ftb-team-logo": HTMLFtbTeamLogoElement;
        "ftb-user-photo": HTMLFtbUserPhotoElement;
    }
}
declare namespace LocalJSX {
    interface CmpShowcase {
    }
    interface FtbIcon {
        "svg": string;
    }
    interface FtbImg {
        "name"?: string;
        "onColor"?: (event: CustomEvent<[number, number, number]>) => void;
        "onFailed"?: (event: CustomEvent<boolean>) => void;
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "src": string;
    }
    interface FtbPlayerPhoto {
        "player"?: Player;
        "playerId"?: number;
        "version"?: number;
    }
    interface FtbTeamLogo {
        "logo"?: string;
        "mode"?: FtbTeamLogoMode;
        "name"?: string;
        "team"?: Team;
        "version"?: number;
    }
    interface FtbUserPhoto {
        "user"?: User;
        "userId"?: number;
        "version"?: number;
    }
    interface IntrinsicElements {
        "cmp-showcase": CmpShowcase;
        "ftb-icon": FtbIcon;
        "ftb-img": FtbImg;
        "ftb-player-photo": FtbPlayerPhoto;
        "ftb-team-logo": FtbTeamLogo;
        "ftb-user-photo": FtbUserPhoto;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cmp-showcase": LocalJSX.CmpShowcase & JSXBase.HTMLAttributes<HTMLCmpShowcaseElement>;
            "ftb-icon": LocalJSX.FtbIcon & JSXBase.HTMLAttributes<HTMLFtbIconElement>;
            "ftb-img": LocalJSX.FtbImg & JSXBase.HTMLAttributes<HTMLFtbImgElement>;
            "ftb-player-photo": LocalJSX.FtbPlayerPhoto & JSXBase.HTMLAttributes<HTMLFtbPlayerPhotoElement>;
            "ftb-team-logo": LocalJSX.FtbTeamLogo & JSXBase.HTMLAttributes<HTMLFtbTeamLogoElement>;
            "ftb-user-photo": LocalJSX.FtbUserPhoto & JSXBase.HTMLAttributes<HTMLFtbUserPhotoElement>;
        }
    }
}
